### ISSUE TITLE
Cannot build database

### ISSUE THREAD

**Issue by JustinChu** [aindj/k-SLAM#1]
I am unable to build a database. Here is the error I am getting:

```
install_slam.sh database_dir bacteria viruses
Downloading RefSeq taxonomy
--2016-07-15 11:25:08--  ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
           => ‘taxdump.tar.gz’
Resolving ftp.ncbi.nih.gov... 130.14.250.13, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nih.gov|130.14.250.13|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy ... done.
==> SIZE taxdump.tar.gz ... 36632222
==> PASV ... done.    ==> RETR taxdump.tar.gz ... done.
Length: 36632222 (35M) (unauthoritative)

taxdump.tar.gz                100%[=================================================>]  34.93M  8.45MB/s    in 4.3s    

2016-07-15 11:25:14 (8.05 MB/s) - ‘taxdump.tar.gz’ saved [36632222]

Decompressing
citations.dmp
delnodes.dmp
division.dmp
gc.prt
gencode.dmp
merged.dmp
names.dmp
nodes.dmp
readme.txt
Done
Downloading RefSeq bacterial genomes
--2016-07-15 11:25:17--  ftp://ftp.ncbi.nih.gov/genomes/Bacteria/all.gbk.tar.gz
           => ‘all.gbk.tar.gz’
Resolving ftp.ncbi.nih.gov... 130.14.250.13, 2607:f220:41e:250::13
Connecting to ftp.ncbi.nih.gov|130.14.250.13|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /genomes/Bacteria ... 
No such directory ‘genomes/Bacteria’.
```

**Comment by aindj** [comment]
The database downloading script is out of date as ncbi very recently changed the whole structure of their FTP site.
I was going to upload the new database script to github when the paper was published but if you would like to use the code sooner then when I return from Florida I will put the new script up.
I should be able to do this early next week
Thanks for the interest in k-slam

On 15 Jul 2016 2:28 p.m., Justin Chu <notifications@github.com> wrote:

I am unable to build a database. Here is the error I am getting:

install_slam.sh database_dir bacteria viruses
Downloading RefSeq taxonomy
--2016-07-15 11:25:08--  ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
           => 'taxdump.tar.gz'
Resolving ftp.ncbi.nih.gov... 130.14.250.13, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nih.gov|130.14.250.13|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy ... done.
==> SIZE taxdump.tar.gz ... 36632222
==> PASV ... done.    ==> RETR taxdump.tar.gz ... done.
Length: 36632222 (35M) (unauthoritative)

taxdump.tar.gz                100%[=================================================>]  34.93M  8.45MB/s    in 4.3s

2016-07-15 11:25:14 (8.05 MB/s) - 'taxdump.tar.gz' saved [36632222]

Decompressing
citations.dmp
delnodes.dmp
division.dmp
gc.prt
gencode.dmp
merged.dmp
names.dmp
nodes.dmp
readme.txt
Done
Downloading RefSeq bacterial genomes
--2016-07-15 11:25:17--  ftp://ftp.ncbi.nih.gov/genomes/Bacteria/all.gbk.tar.gz
           => 'all.gbk.tar.gz'
Resolving ftp.ncbi.nih.gov... 130.14.250.13, 2607:f220:41e:250::13
Connecting to ftp.ncbi.nih.gov|130.14.250.13|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /genomes/Bacteria ...
No such directory 'genomes/Bacteria'.


I tried to see what was being made in the directories:

ls genomes/
bacteria  log.txt  taxDB  taxonomy
ls genomes/bacteria/


genomes/bacteria seems to be empty.

-

**Comment by aindj** [comment]
I have modified the install_slam.sh 
The script should now work correctly
