### ISSUE TITLE
Download the Bacteria and Virus genome database and then?

### ISSUE THREAD

**Issue by mghanbari** [aindj/k-SLAM#11]
Hi

I've downloaded the bacteria and viruses genome databases. How should I build an index from them for the SLAM? Please provide an example.

Regards
Mahdi

**Comment by aindj** [comment]
there are examples in the readme file

**Comment by mghanbari** [comment]
You mean this command? I used it but it gave an error. 

SLAM --output-file database --parse-genbank file1.gbk file2.gbk file3.gbk ...
